### PR TITLE
Test for on-demond CI process

### PR DESCRIPTION
**Pull request by DoyleLi**
Signed-off-by: Xiaodong Li <xiaodong.li@intel.com>
Test for on-demond CI process

### CODE REVIEW

**Comment by DoyleLi** [comment]
Useless comment
/summary:run

**Comment by DoyleLi** [comment]
Will trigger
 haha /summary:run

**Comment by DoyleLi** [comment]
Will not trigger summary:run

**Comment by DoyleLi** [comment]
Will trigger /summary:run

**Comment by DoyleLi** [comment]
This comment will not trigger summary build.

**Comment by DoyleLi** [comment]
This comment will trigger summary build. /summary:run

**Comment by DoyleLi** [comment]
This comment will trigger summary build again
/summary:run

**Comment by bader** [comment]
Let's check if some else can start testing
/summary:run

**Pull request closed without merging**
